# Generated by Django 3.2.9 on 2021-12-16 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='korisnik',
            name='grad',
        ),
        migrations.AlterField(
            model_name='korisnik',
            name='duzina',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='korisnik',
            name='sirina',
            field=models.FloatField(null=True),
        ),
    ]
