# Generated by Django 3.2.9 on 2021-12-29 20:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_auto_20211216_1846'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(blank=True, max_length=50)),
                ('cijena', models.IntegerField(null=True)),
                ('slika', models.ImageField(default='static/img/default1.jpg', upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Restoran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(blank=True, max_length=50)),
                ('kratko', models.TextField(blank=True)),
                ('opis', models.TextField(blank=True)),
                ('sirina', models.FloatField(null=True)),
                ('duzina', models.FloatField(null=True)),
                ('grad', models.CharField(blank=True, max_length=50)),
                ('slika', models.ImageField(default='static/img/default1.jpg', upload_to='images/')),
            ],
        ),
        migrations.AlterField(
            model_name='korisnik',
            name='telefon',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='Narudzba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ukupno', models.IntegerField(default=0)),
                ('potvrdeno', models.BooleanField(default=False)),
                ('meni', models.ManyToManyField(blank=True, to='main.Jelo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='jelo',
            name='restoran',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.restoran'),
        ),
    ]
